import { describe, expect, it } from 'vitest';
import { chooseBestTranscriptCandidate, scoreTranscriptCandidates } from '../src/lib/transcriptDetection';

const chatSample = `31/12/2024, 18:42 - Avi Cohen: <attached: IMG-20241231-WA0001.jpg>
01/01/2025, 09:15 - Dana: hello`;

describe('chooseBestTranscriptCandidate', () => {
  it('prefers _chat.txt when it contains WhatsApp messages', () => {
    const selected = chooseBestTranscriptCandidate([
      { filename: 'WhatsApp Chat with John.txt', sample: chatSample },
      { filename: '_chat.txt', sample: chatSample }
    ]);

    expect(selected?.filename).toBe('_chat.txt');
  });

  it('supports English WhatsApp export transcript names', () => {
    const selected = chooseBestTranscriptCandidate([{ filename: 'WhatsApp Chat with John.txt', sample: chatSample }]);

    expect(selected?.filename).toBe('WhatsApp Chat with John.txt');
  });

  it('supports Hebrew WhatsApp export transcript names', () => {
    const selected = chooseBestTranscriptCandidate([
      { filename: "צ'אט WhatsApp עם יוני אדלר.txt", sample: chatSample }
    ]);

    expect(selected?.filename).toBe("צ'אט WhatsApp עם יוני אדלר.txt");
  });

  it('supports transcript filenames with spaces and apostrophes', () => {
    const selected = chooseBestTranscriptCandidate([
      { filename: "WhatsApp Chat with John's Family Photos.txt", sample: chatSample }
    ]);

    expect(selected?.filename).toBe("WhatsApp Chat with John's Family Photos.txt");
  });

  it('rejects TXT files that are not WhatsApp transcripts', () => {
    const selected = chooseBestTranscriptCandidate([
      { filename: 'readme.txt', sample: 'This archive was generated by another tool.' },
      { filename: 'notes.txt', sample: 'No timestamped sender lines here.' }
    ]);

    expect(selected).toBeNull();
  });

  it('chooses a Hebrew transcript when ZIP-like candidates include media and non-chat TXT files', () => {
    const scored = scoreTranscriptCandidates([
      { filename: 'media/IMG-20241231-WA0001.jpg', sample: '' },
      { filename: 'notes.txt', sample: 'plain notes' },
      { filename: "צ'אט WhatsApp עם יוני אדלר.txt", sample: chatSample }
    ].filter((entry) => entry.filename.endsWith('.txt')));
    const selected = chooseBestTranscriptCandidate(scored);

    expect(selected?.filename).toBe("צ'אט WhatsApp עם יוני אדלר.txt");
  });
});
